export class CommonConstants {
  public static readonly FONT_SIZE_12 = '12fp';
  public static readonly FONT_SIZE_14 = '14fp';
  public static readonly FONT_SIZE_16 = '16fp';
  public static readonly FONT_SIZE_18 = '18fp';
  public static readonly FONT_SIZE_24 = '24fp';
  public static readonly THEME_COLOR = '#7D66FF';

  public static readonly FONT_COLOR_LEVEL1 = '#E6000000';
  public static readonly FONT_COLOR_1_INVERT = '#FFFFFF';
  public static readonly FONT_COLOR_LEVEL2 = '#99000000';
  public static readonly FONT_COLOR_LEVEL3 = '#66000000';
  public static readonly DIVIDER_COLOR = '#33000000';
  public static readonly WARNING_COLOR = '#E84026';
  public static readonly BUTTON_BACKGROUND_COLOR_GREY = '#0D000000';
  public static readonly BACKGROUND_COLOR = '#FFFFFF';
  public static readonly BACKGROUND_COLOR_GREY = '#f1f3f5';
  public static readonly BORDER_RADIUS_16 = '16vp';
}
